# Generated by Django 3.2.18 on 2023-06-06 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Оцените время, потраченное на приготовление рецепта.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки'),
        ),
    ]
