# Generated by Django 3.2.18 on 2023-06-06 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Кол-во'),
        ),
    ]
