# Generated by Django 3.2.18 on 2023-05-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_auto_20230527_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'корзина покупок',
                'verbose_name_plural': 'корзины покупок',
                'ordering': ['recipe'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(db_index=True, max_length=24, verbose_name='Ед-ца измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Оцените время, потраченное на приготовление рецепта.', verbose_name='Время готовки'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'color', 'slug')},
        ),
        migrations.DeleteModel(
            name='ShopingCartUser',
        ),
        migrations.AddField(
            model_name='shoppingcartuser',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_cart', to='recipe.recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartuser',
            unique_together={('owner', 'recipe')},
        ),
    ]
